const MODE_SINGLE_MINUTE_PARSE = 0;
const MODE_SINGLE_MINUTE_WAITLOAD_AND_PARSE = 1;
const MODE_COUNCILS_PARSE = 2;
const MODE_SCHEDULES_SHOW_AND_PARSE_IDS = 3;

const PAGE_MODE_TOP = "t";
const PAGE_MODE_SCHEDULE_DIALOG = "d";
const PAGE_MODE_YEARLY = "y";
const PAGE_MODE_SINGLE = "s";
